### ISSUE TITLE
Change some defaults and add explicit labels

### ISSUE THREAD

**Issue by pseudom** [ezpaarse-project/ezpaarse-logger#7]
default : pre-production
label : what is preprod and prod + add URLs
add buttons in the toolbar for : export, clean images

**Comment by pseudom** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ezLOGGER ++](https://trello.com/c/wX5p2yJJ/138-ezlogger)

**Comment by nojhamster** [comment]
Fixed in #9
